//Dictionnaire des mots
let dictionnaire = [
                    "RESPECTUEUX", 
                    "ASEPTISER", 
                    "RELEVER",
                    "MARIAGE",
                    "SENTIER",
                    "CHEMIN",
                    "HEMORROIDE", 
                    "GRAILLER", 
                    "TRIBU",
                    "ABREGER",
                    "ADEPTE",
                    "REFROTTER",
                    "AEROBIQUE",
                    "FRANGLAISE",
                    "FRIGORIFUGER",
                    "RAVACHIR",
                    "AMPHIDELPHE",
                    "AFFAIBLIR",
                    "REVEILLER",
                    "IMPORTANT",
                    "GOMME",
                    "ASSEMBLAGE",
                    "MEUBLE",
                    "ECOQUETER",
                    "GODRONNER",
                    "CONVENTION",
                    "AUTOCENSURE",
                    "FREQUENTER",
                    "MAGNANIMISER",
                    "CORRECTIONNALISER",
                    "VACCINAL",
                    "ENERGIE"
                ];

dictionnaire = dictionnaire.sort();